var __makeTemplateObject = (this && this.__makeTemplateObject) || function (cooked, raw) {
    if (Object.defineProperty) { Object.defineProperty(cooked, "raw", { value: raw }); } else { cooked.raw = raw; }
    return cooked;
};
import styled from 'styled-components';
//StyledPaginationContainer
var StyledPaginationContainer = styled.div(templateObject_1 || (templateObject_1 = __makeTemplateObject(["\n    text-align: left;\n\n    &[data-pagination-position=\"center\"] {\n        text-align: center;\n    }\n\n    &[data-pagination-position=\"right\"] {\n        text-align: right;\n    }\n\n    ul.pagination {\n        margin: 0;\n        padding-left: 0;\n        border-radius: 4px;\n        display: inline-block;\n\n        > li {\n            display: inline;\n        }\n\n        > li > a, > li > span {\n            position: relative;\n            float: left;\n            width: 36px;\n            height: 36px;\n            margin: 0 5px;\n            padding-top: 7px;\n            text-align: center;\n            line-height: 1.42857143;\n            text-decoration: none;\n            color: ", ";\n            font-size: 14px;\n            border-radius: 25px;\n            background-color: #fff;\n            border: 1px solid #ddd;\n            margin-left: -1px;\n        }\n\n        > .active > a, > .active > span, > .active > a:hover, > .active > span:hover, > .active > a:focus, > .active > span:focus {\n            z-index: 3;\n            color: #fff;\n            background-color: ", ";\n            cursor: default;\n        }\n\n        > li:last-child {\n            display: none;\n        }\n\n        > li.disabled > a {\n            color: #858585;\n            cursor: default;\n        }\n    }\n"], ["\n    text-align: left;\n\n    &[data-pagination-position=\"center\"] {\n        text-align: center;\n    }\n\n    &[data-pagination-position=\"right\"] {\n        text-align: right;\n    }\n\n    ul.pagination {\n        margin: 0;\n        padding-left: 0;\n        border-radius: 4px;\n        display: inline-block;\n\n        > li {\n            display: inline;\n        }\n\n        > li > a, > li > span {\n            position: relative;\n            float: left;\n            width: 36px;\n            height: 36px;\n            margin: 0 5px;\n            padding-top: 7px;\n            text-align: center;\n            line-height: 1.42857143;\n            text-decoration: none;\n            color: ", ";\n            font-size: 14px;\n            border-radius: 25px;\n            background-color: #fff;\n            border: 1px solid #ddd;\n            margin-left: -1px;\n        }\n\n        > .active > a, > .active > span, > .active > a:hover, > .active > span:hover, > .active > a:focus, > .active > span:focus {\n            z-index: 3;\n            color: #fff;\n            background-color: ", ";\n            cursor: default;\n        }\n\n        > li:last-child {\n            display: none;\n        }\n\n        > li.disabled > a {\n            color: #858585;\n            cursor: default;\n        }\n    }\n"])), baseColor, baseColor);
//StyledRatingStarBox
var StyledRatingStarBox = styled.div(templateObject_2 || (templateObject_2 = __makeTemplateObject(["\n    text-align: right;\n    \n    > i {\n        cursor: pointer;\n        color: #ffb700;\n    }\n"], ["\n    text-align: right;\n    \n    > i {\n        cursor: pointer;\n        color: #ffb700;\n    }\n"])));
export { StyledPaginationContainer as PaginationContainer, StyledRatingStarBox as RatingStarBox };
var templateObject_1, templateObject_2;
//# sourceMappingURL=__styledUtils.js.map